-- VHDL Entity atlys.idelay2_block.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library utils;
use utils.pkg_types.all;

library hsio;
use hsio.pkg_core_globals.all;

entity idelay2_block is
   generic( 
      LINK_ID : integer := 0
   );
   port( 
      clk                    : in     std_logic;
      ddrdata_i              : in     std_logic;
      --idelay_ce_o   : out    std_logic_vector (71 downto 0);
      --idelay_inc_o  : out    std_logic;
      --idelay_zero_o : out    std_logic_vector (71 downto 0);
      idelay_ctl_i           : in     t_idelay_ctl;
      loopdata0_i            : in     std_logic;
      loopdata1_i            : in     std_logic;
      rst                    : in     std_logic;
      dbg_ddrdata_idelayed_o : out    std_logic;
      stream0_o              : out    std_logic;
      stream1_o              : out    std_logic
   );

-- Declarations

end idelay2_block ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- atlys.idelay2_block.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library utils;
use utils.pkg_types.all;

library hsio;
use hsio.pkg_core_globals.all;

library unisim;
use unisim.all;


architecture struct of idelay2_block is

   -- Architecture declarations

   -- Internal signal declarations
   signal HI              : std_logic;
   signal LO              : std_logic;
   signal clkn            : std_logic;
   signal ddrdata_delayed : std_logic;
   signal idelay_ce       : std_logic;
   signal idelay_inc      : std_logic;
   signal idelay_zero     : std_logic;
   signal rst_idelay      : std_logic;
   signal stream0         : std_logic;
   signal stream1         : std_logic;
   signal strm_loop       : std_logic;
   signal strm_swap       : std_logic;


   -- Component Declarations
   component IDDR2
   generic (
      DDR_ALIGNMENT : string := "NONE";
      INIT_Q0       : bit    := '0';
      INIT_Q1       : bit    := '0';
      SRTYPE        : string := "SYNC"
   );
   port (
      C0 : in     std_ulogic;
      C1 : in     std_ulogic;
      CE : in     std_ulogic  := 'H';
      D  : in     std_ulogic;
      R  : in     std_ulogic  := 'L';
      S  : in     std_ulogic  := 'L';
      Q0 : out    std_ulogic;
      Q1 : out    std_ulogic
   );
   end component;
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   prc_ff : process (clk)
   begin
     if rising_edge(clk) then
       if (rst = '1') then
         stream0_o <= '0';
         stream1_o <= '0';
   
       else
         --if (strm_loop = '1') then
         --  stream0_o <= loopdata0_i;
         --  stream1_o <= loopdata1_i;
         --else
           if (strm_swap = '0') then
             stream0_o <= stream0;
             stream1_o <= stream1;
           else 
             stream0_o <= stream1;
             stream1_o <= stream0;
           end if;
         --end if;
       end if;
     end if;
   end process;

   -- HDL Embedded Text Block 2 eb2
   -- eb2 2
   idelay_zero <= idelay_ctl_i.zero(LINK_ID);
   idelay_ce <= idelay_ctl_i.ce(LINK_ID);
   idelay_inc <= idelay_ctl_i.inc;
   strm_swap <=  idelay_ctl_i.strm_swap(LINK_ID);
   strm_loop <=  idelay_ctl_i.strm_loop(LINK_ID);


   -- ModuleWare code(v1.12) for instance 'U_1' of 'buff'
   dbg_ddrdata_idelayed_o <= ddrdata_delayed;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'buff'
   ddrdata_delayed <= ddrdata_i;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   clkn <= not(clk);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   rst_idelay <= idelay_zero or rst;

   -- Instance port mappings.
   Uiddr : IDDR2
      generic map (
         DDR_ALIGNMENT => "NONE",
         INIT_Q0       => '0',
         INIT_Q1       => '0',
         SRTYPE        => "SYNC"
      )
      port map (
         Q0 => open,
         Q1 => stream0,
         C0 => clk,
         C1 => clkn,
         CE => HI,
         D  => ddrdata_delayed,
         R  => rst,
         S  => LO
      );
   Umpower : m_power
      port map (
         hi => HI,
         lo => LO
      );

end struct;
