-- timestamp.vhd generated by mkfiles/timestamp.tcl:
-- Thu Oct 09 10:53:33 PM CST 2014 = 1412857413 = 0x54367E45
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity timestamp is
   port( ts_o : out std_logic_vector (31 downto 0));
end timestamp ;

architecture rtl of timestamp is
begin
  ts_o <= conv_std_logic_vector(1412857413, 32);
end architecture rtl;

