-- timestamp.vhd generated by mkfiles/timestamp.tcl:
-- Mon Oct 13 03:05:55 PM CST 2014 = 1413174955 = 0x543B56AB
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity timestamp is
   port( ts_o : out std_logic_vector (31 downto 0));
end timestamp ;

architecture rtl of timestamp is
begin
  ts_o <= conv_std_logic_vector(1413174955, 32);
end architecture rtl;

