onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/clk125
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/clk40
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/hi
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/hyb_data
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/lo
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/mac_source
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/por
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_fifo_rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_ll_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_ll_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_ll_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_ll_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/rx_ll_data
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_fifo_rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/rx_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/rx_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_magicn
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_seq
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_len
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_cbcnt
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_opcode
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_opseq
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_size
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/rx_word0
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/oc_data
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/oc_dtack_all
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/state
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/oc_valid_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbregblock/oc_data_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/oc_dtack_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbregblock/state
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/deser_we
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/deser_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/deser_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/deser_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/udeser/state
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/udeser/bit_counter
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/udeser/word_count
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/udeser/bit_counter_clr
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ru_src_rdy_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ru_sof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ru_eof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ru_dst_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ru_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/state
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/selected_str_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/fifo_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/len_fifo_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/data_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/fifo_din
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/fifo_dout
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/fifo_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/fifo_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/src_rdy_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/dst_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/data_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/grounit__0/uunit/ufifo/state
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/tx_data
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_ll_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_ll_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_ll_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/tx_ll_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/tx_ll_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/utxpktfmt/state
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/utxpktfmt/oc_store(0)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/utxpktfmt/oc_store(1)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/utxpktfmt/oc_store(2)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/utxpktfmt/data_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/utxpktfmt/oc_store_en
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/start_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/abc_gendata_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/len_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/rst
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/byte_counter
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/ureadout/udatagen/state
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/oc_dtack
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/oc_valid
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/oc_dtack_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/oc_dtack_masked
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/tick_1khz_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/watchdog_timer
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/wcount
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/wcount_clr
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/urxpacketdecoder/wcount_en
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/abc_com
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/abc_com_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbrawcom/bitcount40
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/bitcount40_set
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/clk
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbrawcom/nstate
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbrawcom/oc_data_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/oc_dtack_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/oc_valid_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/ocrawcom_start_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/ocseq_store_en
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/rst
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbrawcom/rx_ocseq
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbrawcom/state
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbrawcom/strobe40_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/cbcnt
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/len
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/magicn
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/ocseq
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/opcode
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/seq
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/size
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/words
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/uclkstop/po_ready
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/uclkstop/oa_ready
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/uclkstop/clk80
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/uclkstop/rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/uclkstop/po_rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_src_rdy(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_sof(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_eof(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_dst_rdy(63)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_data(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_src_rdy(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_sof(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_eof(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/s_dst_rdy(61)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_data(61)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/s_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/tx_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/tx_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/tx_eof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/tx_dst_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/tx_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/sel
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/clk
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/dst_rdy_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_src_rdy_i(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_sof_i(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_eof_i(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_dst_rdy_o(63)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_data_i(63)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_data_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_eof_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_sof_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_src_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/data_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/s_dst_rdy_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/selected_str_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/sof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/eof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/src_rdy_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/freeze
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/data_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/sof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/eof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/src_rdy_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/freeze_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/s_data_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/s_sof_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/s_eof_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/s_src_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/sel_i
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/clk
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/rst
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_dst_rdy_o(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/a_src_rdy
add wave -noupdate -format Logic -radix binary /main_top_tb/umain/umux64/usmx64/a_sof
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_src_rdy(1)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_sof(1)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_src_rdy(3)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_sof(3)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_src_rdy(7)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_sof(7)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_src_rdy(15)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_sof(15)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_src_rdy(30)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_sof(30)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_src_rdy(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_sof(61)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_eof(61)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_sel
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/s_dst_rdy_o(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_sof(31)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_eof(31)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_src_rdy(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_sof(63)
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_eof(63)
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/a_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/a_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/a_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/b_src_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/c_src_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/d_src_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/e_src_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/f_src_rdy
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_sel
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_data
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_sof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_eof
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/usmx64/g_src_rdy
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/src_rdy_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/sof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/eof_o
add wave -noupdate -format Logic -radix hexadecimal /main_top_tb/umain/uocbregblock/dst_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbregblock/data_o
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/uocbregblock/state
add wave -noupdate -format Logic /main_top_tb/umain/umux64/src_rdy_o
add wave -noupdate -format Logic /main_top_tb/umain/umux64/sof_o
add wave -noupdate -format Logic /main_top_tb/umain/umux64/eof_o
add wave -noupdate -format Logic /main_top_tb/umain/umux64/dst_rdy_i
add wave -noupdate -format Literal -radix hexadecimal /main_top_tb/umain/umux64/data_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 7} {98928000 ps} 0} {{Cursor 2} {4395626 ps} 0}
configure wave -namecolwidth 300
configure wave -valuecolwidth 133
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {4311071 ps} {6137182 ps}
