-- VHDL Entity abc130_driver.clocks_resets.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity clocks_resets is
   port( 
      hsio_bco_in : in     std_ulogic;
      rst_ext     : in     std_logic;
      clk160_o    : out    std_logic;
      clk40_o     : out    std_logic;
      clk80_o     : out    std_logic;
      clkn160_o   : out    std_ulogic;
      clkn40_o    : out    std_logic;
      clkn80_o    : out    std_logic;
      rst_o       : out    std_logic;
      strobe40_o  : out    std_logic
   );

-- Declarations

end clocks_resets ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- abc130_driver.clocks_resets.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;


architecture struct of clocks_resets is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk40      : std_logic;
   signal clk80      : std_logic;
   signal dcm_locked : std_logic;
   signal rst        : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_30' of 'adff'
   signal mw_U_30reg_cval : std_logic;

   -- Component Declarations
   component cg_dcm_4080160
   port (
      CLKIN_IN     : in     std_logic ;
      USER_RST_IN  : in     std_logic ;
      CLKFX_OUT    : out    std_logic ;
      CLKFX180_OUT : out    std_logic ;
      CLK0_OUT     : out    std_logic ;
      CLK2X_OUT    : out    std_logic ;
      CLK2X180_OUT : out    std_logic ;
      CLK180_OUT   : out    std_logic ;
      LOCKED_OUT   : out    std_logic 
   );
   end component;
   component strobe40_gen
   port (
      clk        : in     std_logic;
      clk40      : in     std_logic;
      rst        : in     std_logic;
      strobe40_o : out    std_logic
   );
   end component;


begin

   -- ModuleWare code(v1.12) for instance 'U_30' of 'adff'
   rst <= not(mw_U_30reg_cval);
   prcu_30seq: process (clk40)begin
      if (clk40'event and clk40='1') then
         mw_U_30reg_cval <= dcm_locked;
      end if;
   end process prcu_30seq;

   -- ModuleWare code(v1.12) for instance 'U_33' of 'buff'
   clk40_o <= clk40;

   -- ModuleWare code(v1.12) for instance 'U_34' of 'buff'
   clk80_o <= clk80;

   -- ModuleWare code(v1.12) for instance 'U_38' of 'buff'
   rst_o <= rst;

   -- Instance port mappings.
   Udcm : cg_dcm_4080160
      port map (
         CLKIN_IN     => hsio_bco_in,
         USER_RST_IN  => rst_ext,
         CLKFX_OUT    => clk160_o,
         CLKFX180_OUT => clkn160_o,
         CLK0_OUT     => clk40,
         CLK2X_OUT    => clk80,
         CLK2X180_OUT => clkn80_o,
         CLK180_OUT   => clkn40_o,
         LOCKED_OUT   => dcm_locked
      );
   Ustrb40 : strobe40_gen
      port map (
         strobe40_o => strobe40_o,
         clk40      => clk40,
         rst        => rst,
         clk        => clk80
      );

end struct;
