-- VHDL Entity abc_emu.mod130_top.symbol
--
-- Created:
--          by - warren.warren (mbb)
--          at - 09:56:35 06/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity mod130_top is
   generic( 
      CHIPS_PER_CHAIN0 : integer := 5;
      PADID_MIN0       : integer := 1;
      CHIPS_PER_CHAIN1 : integer := 5;      -- 
      PADID_MIN1       : integer := 17      -- 
   );
   port( 
      bco_i      : in     std_logic;
      com_i      : in     std_logic;
      dat00_i    : in     std_logic;
      dat01_i    : in     std_logic;
      dat02_i    : in     std_logic;
      dat03_i    : in     std_logic;
      dat10_i    : in     std_logic;
      dat11_i    : in     std_logic;
      dat12_i    : in     std_logic;
      dat13_i    : in     std_logic;
      dclk_i     : in     std_logic;
      fastclk_i  : in     std_logic;
      l0_i       : in     std_logic;
      l1_i       : in     std_logic;
      r3s_i      : in     std_logic;
      rst_i      : in     std_logic;
      rst_por_ni : in     std_logic;
      xoff00_i   : in     std_logic;
      xoff01_i   : in     std_logic;
      xoff02_i   : in     std_logic;
      xoff03_i   : in     std_logic;
      xoff10_i   : in     std_logic;
      xoff11_i   : in     std_logic;
      xoff12_i   : in     std_logic;
      xoff13_i   : in     std_logic;
      dat00_o    : out    std_logic;
      dat01_o    : out    std_logic;
      dat02_o    : out    std_logic;
      dat03_o    : out    std_logic;
      dat10_o    : out    std_logic;
      dat11_o    : out    std_logic;
      dat12_o    : out    std_logic;
      dat13_o    : out    std_logic;
      xoff00_o   : out    std_logic;
      xoff01_o   : out    std_logic;
      xoff02_o   : out    std_logic;
      xoff03_o   : out    std_logic;
      xoff10_o   : out    std_logic;
      xoff11_o   : out    std_logic;
      xoff12_o   : out    std_logic;
      xoff13_o   : out    std_logic
   );

-- Declarations

end mod130_top ;

--
-- VHDL Architecture abc_emu.mod130_top.struct
--
-- Created:
--          by - warren.warren (mbb)
--          at - 09:56:35 06/03/13
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;


architecture struct of mod130_top is

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   component mod130_hybrid
   generic (
      CHIPS_PER_CHAIN : integer := 5;
      PADID_MIN       : integer := 5
   );
   port (
      bco_i      : in     std_logic ;
      com_i      : in     std_logic ;
      dat0_i     : in     std_logic ;
      dat1_i     : in     std_logic ;
      dat2_i     : in     std_logic ;
      dat3_i     : in     std_logic ;
      dclk_i     : in     std_logic ;
      fastclk_i  : in     std_logic ;
      l0_i       : in     std_logic ;
      l1_i       : in     std_logic ;
      r3s_i      : in     std_logic ;
      rst_i      : in     std_logic ;
      rst_por_ni : in     std_logic ;
      xoff0_i    : in     std_logic ;
      xoff1_i    : in     std_logic ;
      xoff2_i    : in     std_logic ;
      xoff3_i    : in     std_logic ;
      dat0_o     : out    std_logic ;
      dat1_o     : out    std_logic ;
      dat2_o     : out    std_logic ;
      dat3_o     : out    std_logic ;
      xoff0_o    : out    std_logic ;
      xoff1_o    : out    std_logic ;
      xoff2_o    : out    std_logic ;
      xoff3_o    : out    std_logic 
   );
   end component;


begin

   -- Instance port mappings.
   Uhyb0 : mod130_hybrid
      generic map (
         CHIPS_PER_CHAIN => CHIPS_PER_CHAIN0,
         PADID_MIN       => PADID_MIN0
      )
      port map (
         bco_i      => bco_i,
         com_i      => com_i,
         dat0_i     => dat00_i,
         dat1_i     => dat01_i,
         dat2_i     => dat02_i,
         dat3_i     => dat03_i,
         dclk_i     => dclk_i,
         fastclk_i  => fastclk_i,
         l0_i       => l0_i,
         l1_i       => l1_i,
         r3s_i      => r3s_i,
         rst_i      => rst_i,
         rst_por_ni => rst_por_ni,
         xoff0_i    => xoff00_i,
         xoff1_i    => xoff01_i,
         xoff2_i    => xoff02_i,
         xoff3_i    => xoff03_i,
         dat0_o     => dat00_o,
         dat1_o     => dat01_o,
         dat2_o     => dat02_o,
         dat3_o     => dat03_o,
         xoff0_o    => xoff00_o,
         xoff1_o    => xoff01_o,
         xoff2_o    => xoff02_o,
         xoff3_o    => xoff03_o
      );
   Uhyb1 : mod130_hybrid
      generic map (
         CHIPS_PER_CHAIN => CHIPS_PER_CHAIN1,
         PADID_MIN       => PADID_MIN1
      )
      port map (
         bco_i      => bco_i,
         com_i      => com_i,
         dat0_i     => dat10_i,
         dat1_i     => dat11_i,
         dat2_i     => dat12_i,
         dat3_i     => dat13_i,
         dclk_i     => dclk_i,
         fastclk_i  => fastclk_i,
         l0_i       => l0_i,
         l1_i       => l1_i,
         r3s_i      => r3s_i,
         rst_i      => rst_i,
         rst_por_ni => rst_por_ni,
         xoff0_i    => xoff10_i,
         xoff1_i    => xoff11_i,
         xoff2_i    => xoff12_i,
         xoff3_i    => xoff13_i,
         dat0_o     => dat10_o,
         dat1_o     => dat11_o,
         dat2_o     => dat12_o,
         dat3_o     => dat13_o,
         xoff0_o    => xoff10_o,
         xoff1_o    => xoff11_o,
         xoff2_o    => xoff12_o,
         xoff3_o    => xoff13_o
      );

end struct;
