--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : cg_dcm_bco_delay.vhd
-- /___/   /\     Timestamp : 06/10/2014 12:09:25
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/warren/slhc/trunk/hsio/coregen/./cg_dcm_bco_delay.xaw /home/warren/slhc/trunk/hsio/coregen/./cg_dcm_bco_delay
--Design Name: cg_dcm_bco_delay
--Device: xc4vfx60-11ff1152
--
-- Module cg_dcm_bco_delay
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: Precision

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity cg_dcm_bco_delay is
   port ( CLKIN_IN     : in    std_logic; 
          DADDR_IN     : in    std_logic_vector (6 downto 0); 
          DCLK_IN      : in    std_logic; 
          DEN_IN       : in    std_logic; 
          DI_IN        : in    std_logic_vector (15 downto 0); 
          DWE_IN       : in    std_logic; 
          PSCLK_IN     : in    std_logic; 
          PSEN_IN      : in    std_logic; 
          PSINCDEC_IN  : in    std_logic; 
          RST_IN       : in    std_logic; 
          CLK0_OUT     : out   std_logic; 
          CLK2X_OUT    : out   std_logic; 
          CLK2X180_OUT : out   std_logic; 
          CLK90_OUT    : out   std_logic; 
          CLK180_OUT   : out   std_logic; 
          CLK270_OUT   : out   std_logic; 
          DRDY_OUT     : out   std_logic; 
          LOCKED_OUT   : out   std_logic; 
          PSDONE_OUT   : out   std_logic);
end cg_dcm_bco_delay;

architecture BEHAVIORAL of cg_dcm_bco_delay is
   attribute CLK_FEEDBACK          : string ;
   attribute CLKDV_DIVIDE          : string ;
   attribute CLKFX_DIVIDE          : string ;
   attribute CLKFX_MULTIPLY        : string ;
   attribute CLKIN_DIVIDE_BY_2     : string ;
   attribute CLKIN_PERIOD          : string ;
   attribute CLKOUT_PHASE_SHIFT    : string ;
   attribute DCM_AUTOCALIBRATION   : string ;
   attribute DCM_PERFORMANCE_MODE  : string ;
   attribute DESKEW_ADJUST         : string ;
   attribute DFS_FREQUENCY_MODE    : string ;
   attribute DLL_FREQUENCY_MODE    : string ;
   attribute DUTY_CYCLE_CORRECTION : string ;
   attribute FACTORY_JF            : string ;
   attribute PHASE_SHIFT           : string ;
   attribute STARTUP_WAIT          : string ;
   signal CLKFB_IN     : std_logic;
   signal CLK0_BUF     : std_logic;
   component BUFG
      port ( I : in    std_logic; 
             O : out   std_logic);
   end component;
   
   component DCM_ADV
      -- synopsys translate_off
      generic( CLK_FEEDBACK : string :=  "1X";
               CLKDV_DIVIDE : real :=  2.0;
               CLKFX_DIVIDE : integer :=  1;
               CLKFX_MULTIPLY : integer :=  4;
               CLKIN_DIVIDE_BY_2 : boolean :=  FALSE;
               CLKIN_PERIOD : real :=  10.0;
               CLKOUT_PHASE_SHIFT : string :=  "NONE";
               DCM_AUTOCALIBRATION : boolean :=  TRUE;
               DCM_PERFORMANCE_MODE : string :=  "MAX_SPEED";
               DESKEW_ADJUST : string :=  "SYSTEM_SYNCHRONOUS";
               DFS_FREQUENCY_MODE : string :=  "LOW";
               DLL_FREQUENCY_MODE : string :=  "LOW";
               DUTY_CYCLE_CORRECTION : boolean :=  TRUE;
               FACTORY_JF : bit_vector :=  x"F0F0";
               PHASE_SHIFT : integer :=  0;
               STARTUP_WAIT : boolean :=  FALSE;
               SIM_DEVICE : string :=  "VIRTEX4");
      -- synopsys translate_on
      port ( CLKIN    : in    std_logic; 
             CLKFB    : in    std_logic; 
             DADDR    : in    std_logic_vector (6 downto 0); 
             DI       : in    std_logic_vector (15 downto 0); 
             DWE      : in    std_logic; 
             DEN      : in    std_logic; 
             DCLK     : in    std_logic; 
             RST      : in    std_logic; 
             PSEN     : in    std_logic; 
             PSINCDEC : in    std_logic; 
             PSCLK    : in    std_logic; 
             CLK0     : out   std_logic; 
             CLK90    : out   std_logic; 
             CLK180   : out   std_logic; 
             CLK270   : out   std_logic; 
             CLKDV    : out   std_logic; 
             CLK2X    : out   std_logic; 
             CLK2X180 : out   std_logic; 
             CLKFX    : out   std_logic; 
             CLKFX180 : out   std_logic; 
             DRDY     : out   std_logic; 
             DO       : out   std_logic_vector (15 downto 0); 
             LOCKED   : out   std_logic; 
             PSDONE   : out   std_logic);
   end component;
   
   attribute CLK_FEEDBACK of DCM_ADV_INST : label is "1X";
   attribute CLKDV_DIVIDE of DCM_ADV_INST : label is "2.0";
   attribute CLKFX_DIVIDE of DCM_ADV_INST : label is "1";
   attribute CLKFX_MULTIPLY of DCM_ADV_INST : label is "4";
   attribute CLKIN_DIVIDE_BY_2 of DCM_ADV_INST : label is "FALSE";
   attribute CLKIN_PERIOD of DCM_ADV_INST : label is "23.810";
   attribute CLKOUT_PHASE_SHIFT of DCM_ADV_INST : label is "VARIABLE_POSITIVE";
   attribute DCM_AUTOCALIBRATION of DCM_ADV_INST : label is "TRUE";
   attribute DCM_PERFORMANCE_MODE of DCM_ADV_INST : label is "MAX_SPEED";
   attribute DESKEW_ADJUST of DCM_ADV_INST : label is "SYSTEM_SYNCHRONOUS";
   attribute DFS_FREQUENCY_MODE of DCM_ADV_INST : label is "LOW";
   attribute DLL_FREQUENCY_MODE of DCM_ADV_INST : label is "LOW";
   attribute DUTY_CYCLE_CORRECTION of DCM_ADV_INST : label is "TRUE";
   attribute FACTORY_JF of DCM_ADV_INST : label is "F0F0";
   attribute PHASE_SHIFT of DCM_ADV_INST : label is "0";
   attribute STARTUP_WAIT of DCM_ADV_INST : label is "FALSE";
begin
   CLK0_OUT <= CLKFB_IN;
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
   DCM_ADV_INST : DCM_ADV
   -- synopsys translate_off
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 23.810,
            CLKOUT_PHASE_SHIFT => "VARIABLE_POSITIVE",
            DCM_AUTOCALIBRATION => TRUE,
            DCM_PERFORMANCE_MODE => "MAX_SPEED",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"F0F0",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
   -- synopsys translate_on
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IN,
                DADDR(6 downto 0)=>DADDR_IN(6 downto 0),
                DCLK=>DCLK_IN,
                DEN=>DEN_IN,
                DI(15 downto 0)=>DI_IN(15 downto 0),
                DWE=>DWE_IN,
                PSCLK=>PSCLK_IN,
                PSEN=>PSEN_IN,
                PSINCDEC=>PSINCDEC_IN,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>open,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>CLK2X_OUT,
                CLK2X180=>CLK2X180_OUT,
                CLK90=>CLK90_OUT,
                CLK180=>CLK180_OUT,
                CLK270=>CLK270_OUT,
                DO=>open,
                DRDY=>DRDY_OUT,
                LOCKED=>LOCKED_OUT,
                PSDONE=>PSDONE_OUT);
   
end BEHAVIORAL;


