-- VHDL Entity ocb.ocb_streams_tb.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

library utils;
use utils.pkg_types.all;

library hsio;
use hsio.pkg_core_globals.all;


entity ocb_streams_tb is
-- Declarations

end ocb_streams_tb ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- ocb.ocb_streams_tb.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library utils;
use utils.pkg_types.all;
library hsio;
use hsio.pkg_hsio_globals.all;


architecture struct of ocb_streams_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk           : std_logic;
   signal hi            : std_logic;
   signal lo            : std_logic;
   -- hsio oc bus
   signal oc_data       : std_logic_vector(15 downto 0);
   signal oc_dtack      : slv32 := x"00000000";
   signal oc_valid      : std_logic;
   signal rst           : std_logic;
   signal strm_cmd_o    : slv16_array(31 downto 0);
   signal strm_reg      : slv16_array(31 downto 0);
   -- streams interface
   signal strm_req_stat : std_logic_vector(111 downto 0);
   signal tx_data       : slv16;
   signal tx_eof        : std_logic;
   signal tx_sof        : std_logic;
   -- locallink tx interface
   signal tx_src_rdy    : std_logic;


   -- Component Declarations
   component ocb_streams
   generic (
      NSTREAMS : integer := 16
   );
   port (
      -- locallink tx interface
      lls_o           : out    t_llsrc ;
      lld_i           : in     std_logic ;
      -- oc rx interface
      oc_valid_i      : in     std_logic ;
      oc_data_i       : in     slv16 ;
      oc_dack_no      : out    std_logic ;
      -- streams interface
      strm_req_stat_o : out    std_logic_vector ((NSTREAMS-1) downto 0);
      strm_reg_o      : out    slv16_array ((NSTREAMS-1) downto 0);
      strm_cmd_o      : out    slv16_array ((NSTREAMS-1) downto 0);
      -- infrastructure
      clk             : in     std_logic ;
      rst             : in     std_logic 
   );
   end component;
   component ocb_tb_tester
   generic (
      N_OPCODES : integer := 1
   );
   port (
      oc_dtack_i : in     slv32;
      clk_o      : out    std_logic;
      oc_data_o  : out    slv16;
      oc_valid_o : out    std_logic;
      rst_o      : out    std_logic
   );
   end component;
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;


begin

   -- Instance port mappings.
   Uocbstreams : ocb_streams
      generic map (
         NSTREAMS => 32
      )
      port map (
         lls_o           => open,
         lld_i           => hi,
         oc_valid_i      => oc_valid,
         oc_data_i       => oc_data,
         oc_dack_no      => oc_dtack(0),
         strm_req_stat_o => strm_req_stat,
         strm_reg_o      => strm_reg,
         strm_cmd_o      => strm_cmd_o,
         clk             => clk,
         rst             => rst
      );
   Utst : ocb_tb_tester
      generic map (
         N_OPCODES => 1
      )
      port map (
         oc_data_o  => oc_data,
         oc_valid_o => oc_valid,
         oc_dtack_i => oc_dtack,
         clk_o      => clk,
         rst_o      => rst
      );
   Um_power : m_power
      port map (
         hi => hi,
         lo => lo
      );

end struct;
