#!/bin/bash

FNAME=itsdaq_top
ISEDIR=.
WEBDIR=~/public_html/upgrade/firmware
TMPDIR=/tmp/warren/ise/atlys_adaq

echo
echo Doing:

if [ $TMPDIR/$FNAME.bit -nt $ISEDIR/$FNAME.bit ]
then
  echo TMP .bit FILE NEWER! Copying ...
  echo cp -p $TMPDIR/$FNAME.bit $ISEDIR
       cp -p $TMPDIR/$FNAME.bit $ISEDIR
fi


ORIGFN=$FNAME.$2
DESTFN=${FNAME}_$1.$2

echo cp -p $ORIGFN $DESTFN
     cp -p $ORIGFN $DESTFN

echo cp -p $DESTFN $WEBDIR
     cp -p $DESTFN $WEBDIR

echo cp -p $ORIGFN $WEBDIR
     cp -p $ORIGFN $WEBDIR

echo cp -p ../../hsio/src/CHANGELOG.TXT $WEBDIR
     cp -p ../../hsio/src/CHANGELOG.TXT $WEBDIR

