--------------------------------------------------------------------------------
-- Copyright (c) 1995-2013 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.7
--  \   \         Application : xaw2vhdl
--  /   /         Filename : cg_dcm_4080160.vhd
-- /___/   /\     Timestamp : 03/25/2014 12:37:50
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-st /home/warren/slhc/trunk/abc130_driver/coregen/./cg_dcm_4080160.xaw /home/warren/slhc/trunk/abc130_driver/coregen/./cg_dcm_4080160
--Design Name: cg_dcm_4080160
--Device: xc3s50a-5tq144
--
-- Module cg_dcm_4080160
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- Period Jitter (unit interval) for block DCM_SP_INST = 0.11 UI
-- Period Jitter (Peak-to-Peak) for block DCM_SP_INST = 0.71 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity cg_dcm_4080160 is
   port ( CLKIN_IN     : in    std_logic; 
          USER_RST_IN  : in    std_logic; 
          CLKFX_OUT    : out   std_logic; 
          CLKFX180_OUT : out   std_logic; 
          CLK0_OUT     : out   std_logic; 
          CLK2X_OUT    : out   std_logic; 
          CLK2X180_OUT : out   std_logic; 
          CLK180_OUT   : out   std_logic; 
          LOCKED_OUT   : out   std_logic);
end cg_dcm_4080160;

architecture BEHAVIORAL of cg_dcm_4080160 is
   signal CLKFB_IN     : std_logic;
   signal CLK0_BUF     : std_logic;
   signal CLK2X_BUF    : std_logic;
   signal FDS_Q_OUT    : std_logic;
   signal FD1_Q_OUT    : std_logic;
   signal FD2_Q_OUT    : std_logic;
   signal FD3_Q_OUT    : std_logic;
   signal GND_BIT      : std_logic;
   signal OR3_O_OUT    : std_logic;
   signal RST_IN       : std_logic;
begin
   GND_BIT <= '0';
   CLK0_OUT <= CLKFB_IN;
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
   CLK2X_BUFG_INST : BUFG
      port map (I=>CLK2X_BUF,
                O=>CLK2X_OUT);
   
   DCM_SP_INST : DCM_SP
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 1,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 25.000,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"C080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => TRUE)
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IN,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>CLKFX_OUT,
                CLKFX180=>CLKFX180_OUT,
                CLK0=>CLK0_BUF,
                CLK2X=>CLK2X_BUF,
                CLK2X180=>CLK2X180_OUT,
                CLK90=>open,
                CLK180=>CLK180_OUT,
                CLK270=>open,
                LOCKED=>LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   FDS_INST : FDS
      port map (C=>CLKIN_IN,
                D=>GND_BIT,
                S=>GND_BIT,
                Q=>FDS_Q_OUT);
   
   FD1_INST : FD
      port map (C=>CLKIN_IN,
                D=>FDS_Q_OUT,
                Q=>FD1_Q_OUT);
   
   FD2_INST : FD
      port map (C=>CLKIN_IN,
                D=>FD1_Q_OUT,
                Q=>FD2_Q_OUT);
   
   FD3_INST : FD
      port map (C=>CLKIN_IN,
                D=>FD2_Q_OUT,
                Q=>FD3_Q_OUT);
   
   OR2_INST : OR2
      port map (I0=>USER_RST_IN,
                I1=>OR3_O_OUT,
                O=>RST_IN);
   
   OR3_INST : OR3
      port map (I0=>FD3_Q_OUT,
                I1=>FD2_Q_OUT,
                I2=>FD1_Q_OUT,
                O=>OR3_O_OUT);
   
end BEHAVIORAL;


