
rem Clean up the results directory
rmdir /S /Q results
mkdir results

echo 'Synthesizing sample design with XST'
xst -ifn xst.scr
copy eth_gmii_example_design.ngc .\results\eth_gmii_top.ngc

rem  Copy the constraints files generated by Coregen
echo 'Copying files from constraints directory to results directory'
copy ..\example_design\eth_gmii_block.ucf results\eth_gmii_top.ucf

cd results

echo 'Running ngdbuild'
ngdbuild -uc eth_gmii_top.ucf eth_gmii_top

echo 'Running map'
map -timing -ol high eth_gmii_top -o mapped.ncd

echo 'Running par'
par -ol high -w mapped.ncd routed.ncd mapped.pcf

echo 'Running trce'
trce -u -e 10 routed -o routed mapped.pcf

echo 'Running design through bitgen'
bitgen -w routed

echo 'Running netgen to create gate level VHDL model'
netgen -ofmt vhdl -sim -pcf mapped.pcf -dir . -tm eth_gmii_example_design -w routed.ncd routed.vhd
