-- VHDL Entity ethernet_v4.EthStatDecoder_tb.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

entity EthStatDecoder_tb is
-- Declarations

end EthStatDecoder_tb ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- ethernet_v4.EthStatDecoder_tb.sim
--
-- Created by Matt Warren 2014
--




architecture sim of EthStatDecoder_tb is

   -- Architecture declarations

   -- Internal signal declarations
   -- Architecture declarations

   -- Internal signal declarations
   signal rx_clk           : std_logic;
   signal tx_clk           : std_logic;
   signal rst              : std_logic;
   signal tx_stats_i       : std_logic;
   signal tx_stats_valid_i : std_logic;
   signal tx_status_o      : std_logic_vector(31 downto 0);
   signal rx_stats_i       : std_logic_vector(6 downto 0);
   signal rx_stats_valid_i : std_logic;
   signal rx_status_o      : std_logic_vector(27 downto 0);


   -- Component Declarations
   component EthStatDecoder_tester
   port (
      rx_status_o      : in     std_logic_vector (27 downto 0);
      tx_status_o      : in     std_logic_vector (31 downto 0);
      rst              : out    std_logic;
      rx_clk           : out    std_logic;
      rx_stats_i       : out    std_logic_vector (6 downto 0);
      rx_stats_valid_i : out    std_logic;
      tx_clk           : out    std_logic;
      tx_stats_i       : out    std_logic;
      tx_stats_valid_i : out    std_logic
   );
   end component;
   component eth_stat_decoder
   port (
      rst              : in     std_logic;
      rx_clk           : in     std_logic;
      rx_stats_i       : in     std_logic_vector (6 downto 0);
      rx_stats_valid_i : in     std_logic;
      tx_clk           : in     std_logic;
      tx_stats_i       : in     std_logic;
      tx_stats_valid_i : in     std_logic;
      rx_status_o      : out    std_logic_vector (27 downto 0);
      tx_status_o      : out    std_logic_vector (31 downto 0)
   );
   end component;


begin

   -- Instance port mappings.
   Ueth_stat_decoder_tester : EthStatDecoder_tester
      port map (
         rx_status_o      => rx_status_o,
         tx_status_o      => tx_status_o,
         rst              => rst,
         rx_clk           => rx_clk,
         rx_stats_i       => rx_stats_i,
         rx_stats_valid_i => rx_stats_valid_i,
         tx_clk           => tx_clk,
         tx_stats_i       => tx_stats_i,
         tx_stats_valid_i => tx_stats_valid_i
      );
   Ueth_stat_decoder : eth_stat_decoder
      port map (
         rx_clk           => rx_clk,
         rst              => rst,
         tx_clk           => tx_clk,
         tx_stats_i       => tx_stats_i,
         tx_stats_valid_i => tx_stats_valid_i,
         tx_status_o      => tx_status_o,
         rx_stats_i       => rx_stats_i,
         rx_stats_valid_i => rx_stats_valid_i,
         rx_status_o      => rx_status_o
      );

end sim;
