-- VHDL Entity hsio.clocks_top_tb.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--



entity clocks_top_tb is
   generic( 
      SIM_MODE : integer := 0
   );
-- Declarations

end clocks_top_tb ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- hsio.clocks_top_tb.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.std_logic_arith.ALL;
use ieee.std_logic_unsigned.ALL;
library hsio;
use hsio.pkg_hsio_globals.ALL;


architecture struct of clocks_top_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk125           : std_logic;
   signal clk156           : std_logic;
   signal clk160_o         : std_logic;
   signal clk40_ext0       : std_logic;
   signal clk40_ext1       : std_logic;
   signal clk40_o          : std_logic;
   signal clk80_o          : std_logic;
   signal clk_ext_on_o     : std_logic;
   signal clks_top_ready_o : std_logic;
   signal net_usb_ready    : std_logic;
   signal por_sw_n         : std_ulogic;
   -- registers
   signal reg              : t_reg_bus;
   signal rst125           : std_logic;
   signal rst_local        : std_ulogic;
   signal rst_o            : std_logic;
   signal stat_o           : std_logic_vector(7 downto 0);
   signal strobe40_o       : std_logic;


   -- Component Declarations
   component clocks_top
   generic (
      SIM_MODE : integer := 0
   );
   port (
      clk125           : in     std_logic ;
      clk156           : in     std_logic ;
      clk40_ext0_i     : in     std_logic ;
      clk40_ext1_i     : in     std_logic ;
      net_usb_ready    : in     std_logic ;
      por_sw_ni        : in     std_ulogic ;
      -- registers
      reg              : in     t_reg_bus ;
      rst_local_i      : in     std_ulogic ;
      clk160_o         : out    std_logic ;
      clk40_o          : out    std_logic ;
      clk80_o          : out    std_logic ;
      clk_ext_on_o     : out    std_logic ;
      clks_top_ready_o : out    std_logic ;
      rst125           : out    std_logic ;
      rst156_o         : out    std_logic ;
      rst_o            : out    std_logic ;
      stat_o           : out    std_logic_vector (7 downto 0);
      strobe40_o       : out    std_logic 
   );
   end component;
   component clocks_top_tester
   port (
      clk125_o        : out    std_logic ;
      clk156_o        : out    std_logic ;
      clk40_ext0_o    : out    std_logic ;
      clk40_ext1_o    : out    std_logic ;
      net_usb_ready_o : out    std_logic ;
      por_sw_no       : out    std_ulogic ;
      -- registers
      reg             : out    t_reg_bus ;
      rst_local_o     : out    std_ulogic 
   );
   end component;


begin

   -- Instance port mappings.
   Udut : clocks_top
      generic map (
         SIM_MODE => 1
      )
      port map (
         clk125           => clk125,
         clk156           => clk156,
         clk40_ext0_i     => clk40_ext0,
         clk40_ext1_i     => clk40_ext1,
         net_usb_ready    => net_usb_ready,
         por_sw_ni        => por_sw_n,
         reg              => reg,
         rst_local_i      => rst_local,
         clk160_o         => clk160_o,
         clk40_o          => clk40_o,
         clk80_o          => clk80_o,
         clk_ext_on_o     => clk_ext_on_o,
         clks_top_ready_o => clks_top_ready_o,
         rst125           => rst125,
         rst156_o         => open,
         rst_o            => rst_o,
         stat_o           => stat_o,
         strobe40_o       => strobe40_o
      );
   Utst : clocks_top_tester
      port map (
         clk125_o        => clk125,
         clk156_o        => clk156,
         clk40_ext0_o    => clk40_ext0,
         clk40_ext1_o    => clk40_ext1,
         net_usb_ready_o => net_usb_ready,
         por_sw_no       => por_sw_n,
         reg             => reg,
         rst_local_o     => rst_local
      );

end struct;
