-- VHDL Entity hsio.clocks_top.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library hsio;
use hsio.pkg_core_globals.all;

entity clocks_top is
   generic( 
      SIM_MODE : integer := 0
   );
   port( 
      clk125           : in     std_logic;
      clk156           : in     std_logic;
      clk40_ext0_i     : in     std_logic;
      clk40_ext1_i     : in     std_logic;
      net_usb_ready    : in     std_logic;
      por_sw_ni        : in     std_ulogic;
      -- registers
      reg              : in     t_reg_bus;
      rst_local_i      : in     std_ulogic;
      clk160_o         : out    std_logic;
      clk40_o          : out    std_logic;
      clk80_o          : out    std_logic;
      clk_ext_on_o     : out    std_logic;
      clks_top_ready_o : out    std_logic;
      rst125           : out    std_logic;
      rst156_o         : out    std_logic;
      rst_o            : out    std_logic;
      stat_o           : out    std_logic_vector (7 downto 0);
      strobe40_o       : out    std_logic
   );

-- Declarations

end clocks_top ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- hsio.clocks_top.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
use ieee.numeric_std.all;
library unisim;
use unisim.vcomponents.all;

library utils;
use utils.pkg_types.all;

library hsio;
use hsio.pkg_core_globals.all;
use hsio.pkg_hsio_globals.all;


architecture struct of clocks_top is

   -- Architecture declarations

   -- Internal signal declarations
   signal HI                : std_logic;
   signal LO                : std_logic;
   signal clk160            : std_logic;
   signal clk40             : std_logic;
   signal clk40_ext1_sel    : std_logic;
   signal clk40_ext_in      : std_logic;
   signal clk40_ext_raw     : std_logic;
   signal clk40e            : std_logic;
   signal clk40i            : std_logic;
   signal clk80             : std_logic;
   signal clk80e            : std_logic;
   signal clk80i            : std_logic;
   signal clk_dcmext_locked : std_ulogic;
   signal clk_ext_en        : std_logic;
   signal clk_ext_sel       : std_logic;
   signal clk_extctl        : std_logic;
   signal clk_mode          : std_logic_vector(1 downto 0);
   signal clkext0_en        : std_logic;
   signal clkext0_en_r      : std_logic;
   signal clkext1_en        : std_logic;
   signal clkext1_en_r      : std_logic;
   signal clks_top_ready    : std_logic;
   signal clks_top_ready_n  : std_logic;
   signal dcm160_locked     : std_logic;
   signal dcm80160_clk_in   : std_logic;
   signal dcm80160_rst_in   : std_logic;
   signal idelayctrl_rdyb0  : std_logic;
   signal idelayctrl_rdyb1  : std_logic;
   signal idelayctrl_rdyt0  : std_logic;
   signal idelayctrl_rdyt1  : std_logic;
   signal oa_ready          : std_logic;
   signal po_ready          : std_logic;
   signal po_rst            : std_logic;
   signal rst               : std_logic;
   signal rst156            : std_logic;
   signal rst_clkext        : std_logic;
   signal rst_clkext0       : std_logic;
   signal rst_dcmext        : std_logic;
   signal strobe40          : std_logic;

   -- Implicit buffer signal declarations
   signal rst125_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_4' of 'adff'
   signal mw_U_4reg_cval : std_logic;

attribute KEEP : string;
attribute KEEP of clk40 : signal is "true";
attribute KEEP of clk80 : signal is "true";
attribute KEEP of clk40_ext_in : signal is "true";
attribute KEEP of rst125 : signal is "true";
attribute KEEP of rst_clkext : signal is "true";
attribute KEEP of rst_clkext0 : signal is "true";
attribute KEEP of rst_dcmext : signal is "true";
attribute KEEP of clks_top_ready : signal is "true";
attribute KEEP of po_ready : signal is "true";
attribute KEEP of clkext0_en : signal is "true";
attribute KEEP of clkext1_en : signal is "true";
attribute KEEP of stat_o : signal is "true";

   -- Component Declarations
   component cg_dcm_125div3
   port (
      CLKIN_IN          : in     std_logic ;
      RST_IN            : in     std_logic ;
      CLKDV_CLKA1D2_OUT : out    std_logic ;
      CLKDV_CLKA1D4_OUT : out    std_logic ;
      CLKDV_CLKA1_OUT   : out    std_logic ;
      CLK0_CLKB1_OUT    : out    std_logic ;
      LOCKED_OUT        : out    std_logic 
   );
   end component;
   component cg_dcm_4080
   port (
      CLKIN_IN   : in     std_logic;
      RST_IN     : in     std_logic;
      CLK0_OUT   : out    std_logic;
      CLK2X_OUT  : out    std_logic;
      LOCKED_OUT : out    std_logic
   );
   end component;
   component cg_dcm_80_160
   port (
      CLKIN_IN   : in     std_logic;
      RST_IN     : in     std_logic;
      CLK0_OUT   : out    std_logic;
      CLK2X_OUT  : out    std_logic;
      LOCKED_OUT : out    std_logic
   );
   end component;
   component xilinx_reset
   port (
      clk      : in     std_ulogic ;
      ready_i  : in     std_logic ;
      reset_no : out    std_ulogic ;
      reset_o  : out    std_ulogic ;
      resetq_o : out    std_logic 
   );
   end component;
   component BUFG
   port (
      I : in     std_ulogic;
      O : out    std_ulogic
   );
   end component;
   component BUFGCTRL
   generic (
      INIT_OUT     : integer := 0;
      PRESELECT_I0 : boolean := false;
      PRESELECT_I1 : boolean := false
   );
   port (
      CE0     : in     std_ulogic;
      CE1     : in     std_ulogic;
      I0      : in     std_ulogic;
      I1      : in     std_ulogic;
      IGNORE0 : in     std_ulogic;
      IGNORE1 : in     std_ulogic;
      S0      : in     std_ulogic;
      S1      : in     std_ulogic;
      O       : out    std_ulogic
   );
   end component;
   component BUFGMUX_VIRTEX4
   port (
      I0 : in     std_ulogic;
      I1 : in     std_ulogic;
      S  : in     std_ulogic;
      O  : out    std_ulogic
   );
   end component;
   component IDELAYCTRL
   port (
      REFCLK : in     std_ulogic;
      RST    : in     std_ulogic;
      RDY    : out    std_ulogic
   );
   end component;
   component count_delay
   generic (
      SIM_MODE : integer := 0;
      BITS     : integer := 16
   );
   port (
      clk    : in     std_logic;
      rst    : in     std_logic;
      done   : out    std_logic;
      done_n : out    std_logic
   );
   end component;
   component edge_detect
   port (
      clk         : in     std_logic;
      d           : in     std_logic;
      falling     : out    std_logic;
      rising      : out    std_logic;
      rising_long : out    std_logic
   );
   end component;
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;
   component pipeline
   generic (
      LEN : integer := 16
   );
   port (
      clk     : in     std_logic;
      clk_en  : in     std_logic;
      pipe_i  : in     std_logic;
      rst     : in     std_logic;
      pipe_no : out    std_logic;
      pipe_o  : out    std_logic
   );
   end component;
   component strobe40_gen
   port (
      strobe40_o : out    std_logic ;
      clk40      : in     std_logic ;
      rst        : in     std_logic ;
      clk        : in     std_logic 
   );
   end component;


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   clkext0_en <= reg(R_IN_ENA)(ENA_CLK0);
   clkext1_en <= reg(R_IN_ENA)(ENA_CLK1);
   clk_mode <= clkext1_en & clkext0_en;
   
   clk_ext_en <= '0' when (clk_mode = "00") else '1';
   clk40_ext1_sel <= '1' when (clk_mode = "10") else '0';
   
   clk40_ext_raw <= clk40_ext1_i when (clk40_ext1_sel = '1') else
                    clk40_ext0_i;

   -- HDL Embedded Text Block 2 eb2
   -- eb2 2
   stat_o(7) <= rst_clkext0;
   stat_o(6) <= rst_dcmext;
   stat_o(5) <= clk40_ext1_sel;
   stat_o(4) <= clk_ext_sel;
   stat_o(3) <= clk_ext_en;
   stat_o(2) <= clks_top_ready;
   stat_o(1) <= clk_dcmext_locked;
   stat_o(0) <= dcm160_locked;


   -- ModuleWare code(v1.12) for instance 'U_4' of 'adff'
   clks_top_ready_o <= mw_U_4reg_cval;
   prcu_4seq: process (clk80, rst125_internal)
   begin
      if (rst125_internal = '1' or rst125_internal = 'H') then
         mw_U_4reg_cval <= '0';
      elsif (clk80'event and clk80='1') then
         mw_U_4reg_cval <= clks_top_ready;
      end if;
   end process prcu_4seq;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   oa_ready <= clks_top_ready and net_usb_ready and po_ready;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and1'
   clk_ext_sel <= clk_ext_en and clk_dcmext_locked;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'buff'
   strobe40_o <= strobe40;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'buff'
   clk80_o <= clk80;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'buff'
   rst156_o <= rst156;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'buff'
   clk160_o <= clk160;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'buff'
   clk_ext_on_o <= clk_ext_sel;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'buff'
   rst_o <= rst;

   -- ModuleWare code(v1.12) for instance 'U_12' of 'buff'
   clk40_o <= clk40;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'buff'
   clk_extctl <= clk80;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'buff'

   -- ModuleWare code(v1.12) for instance 'U_9' of 'inv'
   clks_top_ready_n <= not(clks_top_ready);

   -- ModuleWare code(v1.12) for instance 'Uclkextrst' of 'or'
   rst_clkext0 <= clkext0_en_r or clkext1_en_r or rst;

   -- ModuleWare code(v1.12) for instance 'Upor' of 'or'
   po_rst <= not(por_sw_ni) or rst_local_i;

   -- Instance port mappings.
   Udcm125div3 : cg_dcm_125div3
      port map (
         CLKIN_IN          => clk125,
         RST_IN            => rst125_internal,
         CLKDV_CLKA1D2_OUT => clk40i,
         CLKDV_CLKA1D4_OUT => open,
         CLKDV_CLKA1_OUT   => clk80i,
         CLK0_CLKB1_OUT    => open,
         LOCKED_OUT        => clks_top_ready
      );
   Udcmext : cg_dcm_4080
      port map (
         CLKIN_IN   => clk40_ext_in,
         RST_IN     => rst_dcmext,
         CLK0_OUT   => clk40e,
         CLK2X_OUT  => clk80e,
         LOCKED_OUT => clk_dcmext_locked
      );
   Udcm80160 : cg_dcm_80_160
      port map (
         CLKIN_IN   => dcm80160_clk_in,
         RST_IN     => dcm80160_rst_in,
         CLK0_OUT   => open,
         CLK2X_OUT  => clk160,
         LOCKED_OUT => dcm160_locked
      );
   Uxrst156 : xilinx_reset
      port map (
         clk      => clk156,
         ready_i  => po_ready,
         reset_no => open,
         reset_o  => open,
         resetq_o => rst156
      );
   Uxrst157 : xilinx_reset
      port map (
         clk      => clk80,
         ready_i  => oa_ready,
         reset_no => open,
         reset_o  => open,
         resetq_o => rst
      );
   Uxrstbcodc : xilinx_reset
      port map (
         clk      => dcm80160_clk_in,
         ready_i  => clks_top_ready,
         reset_no => open,
         reset_o  => dcm80160_rst_in,
         resetq_o => open
      );
   Uclkmuxextin : BUFG
      port map (
         O => clk40_ext_in,
         I => clk40_ext_raw
      );
   Ubufgctrl : BUFGCTRL
      generic map (
         INIT_OUT     => 0,
         PRESELECT_I0 => false,
         PRESELECT_I1 => false
      )
      port map (
         O       => dcm80160_clk_in,
         CE0     => HI,
         CE1     => HI,
         I0      => clk125,
         I1      => clk80,
         IGNORE0 => HI,
         IGNORE1 => HI,
         S0      => clks_top_ready_n,
         S1      => clks_top_ready
      );
   Uclkmuxext40 : BUFGMUX_VIRTEX4
      port map (
         O  => clk40,
         I0 => clk40i,
         I1 => clk40e,
         S  => clk_ext_sel
      );
   Uclkmuxext80 : BUFGMUX_VIRTEX4
      port map (
         O  => clk80,
         I0 => clk80i,
         I1 => clk80e,
         S  => clk_ext_sel
      );
   Uidob_idelayctrl0 : IDELAYCTRL
      port map (
         RDY    => idelayctrl_rdyb0,
         REFCLK => clk156,
         RST    => rst156
      );
   Uidob_idelayctrl1 : IDELAYCTRL
      port map (
         RDY    => idelayctrl_rdyb1,
         REFCLK => clk156,
         RST    => rst156
      );
   Uidot_idelayctrl0 : IDELAYCTRL
      port map (
         RDY    => idelayctrl_rdyt0,
         REFCLK => clk156,
         RST    => rst156
      );
   Uidot_idelayctrl1 : IDELAYCTRL
      port map (
         RDY    => idelayctrl_rdyt1,
         REFCLK => clk156,
         RST    => rst156
      );
   Ucountdelay : count_delay
      generic map (
         SIM_MODE => SIM_MODE,
         BITS     => 25
      )
      port map (
         done   => po_ready,
         done_n => rst125_internal,
         rst    => po_rst,
         clk    => clk125
      );
   Ucountdelay1 : count_delay
      generic map (
         SIM_MODE => SIM_MODE,
         BITS     => 25
      )
      port map (
         done   => open,
         done_n => rst_clkext,
         rst    => rst_clkext0,
         clk    => clk_extctl
      );
   Uedclken0 : edge_detect
      port map (
         clk         => clk_extctl,
         d           => clkext0_en,
         rising      => open,
         rising_long => clkext0_en_r,
         falling     => open
      );
   Uedclken1 : edge_detect
      port map (
         clk         => clk_extctl,
         d           => clkext1_en,
         rising      => open,
         rising_long => clkext1_en_r,
         falling     => open
      );
   Umpower : m_power
      port map (
         hi => HI,
         lo => LO
      );
   Uextswdelay : pipeline
      generic map (
         LEN => 16
      )
      port map (
         clk_en  => HI,
         pipe_i  => rst_clkext,
         pipe_o  => rst_dcmext,
         pipe_no => open,
         rst     => LO,
         clk     => clk_extctl
      );
   Ustrobe40gen : strobe40_gen
      port map (
         strobe40_o => strobe40,
         clk40      => clk40,
         rst        => rst,
         clk        => clk80
      );

   -- Implicit buffered output assignments
   rst125 <= rst125_internal;

end struct;
