-- VHDL Entity hsio.top_outputs_tb.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--



entity top_outputs_tb is
-- Declarations

end top_outputs_tb ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- hsio.top_outputs_tb.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.std_logic_arith.ALL;
use ieee.std_logic_unsigned.ALL;


architecture struct of top_outputs_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk            : std_logic;
   signal clk_bco        : std_logic;
   signal com            : std_logic;
   signal ibe_bco_mo     : std_logic;                        -- HARDRESETB (J32.6/J33.14) HRSTB (J26.B3)
   signal ibe_bco_po     : std_logic;                        -- HARDRESET (J32.5/J33.13) HRST (J26.A3)
   signal ibe_bcot_mo    : std_logic;                        -- HARDRESETB (J32.6/J33.14) HRSTB (J26.B3)
   signal ibe_bcot_po    : std_logic;                        -- HARDRESET (J32.5/J33.13) HRST (J26.A3)
   signal ibepp0_bc_mo   : std_logic;                        -- CLKB (J33.4) CLKLB (J26.D4)
   signal ibepp0_bc_po   : std_logic;                        -- CLK (J33.3) CLKL (J26.C4)
   signal ibepp0_clk_mo  : std_logic;                        -- CLKB (J33.4) CLKLB (J26.D4)
   signal ibepp0_clk_po  : std_logic;                        -- CLK (J33.3) CLKL (J26.C4)
   signal ibepp1_bc_mo   : std_logic;                        -- CLKB (J33.4) CLKLB (J26.D4)
   signal ibepp1_bc_po   : std_logic;                        -- CLK (J33.3) CLKL (J26.C4)
   signal ibepp1_clk_mo  : std_logic;                        -- BCB (J32.4/J33.8) SW_CLKB (J26.F4)
   signal ibepp1_clk_po  : std_logic;                        -- BC (J32.3/J33.7) SW_CLK (J26.E4)
   signal ibpp0_o        : std_logic_vector(7 downto 0);
   signal ibpp1_o        : std_logic_vector(7 downto 0);
   signal l1r            : std_logic;
   signal outsigs        : std_logic_vector(15 downto 0);
   signal reg_com_enable : std_logic_vector(15 downto 0);
   signal reg_control    : std_logic_vector(15 downto 0);
   signal rst            : std_logic;
   signal strobe40       : std_logic;


   -- Component Declarations
   component top_outputs
   port (
      clk              : in     std_logic ;
      clk_bco_i        : in     std_logic ;
      com_i            : in     std_logic ;
      outsigs_i        : in     std_logic_vector (15 downto 0);
      reg_com_enable_i : in     std_logic_vector (15 downto 0);
      reg_control_i    : in     std_logic_vector (15 downto 0);
      rst              : in     std_logic ;
      strobe40_i       : in     std_logic ;
      dbg_outsigs_o    : out    std_logic_vector (15 downto 0);
      ibe_bco_mo       : out    std_logic ;                   -- HARDRESETB (J32.6/J33.14) HRSTB (J26.B3)
      ibe_bco_po       : out    std_logic ;                   -- HARDRESET (J32.5/J33.13) HRST (J26.A3)
      ibe_bcot_mo      : out    std_logic ;                   -- HARDRESETB (J32.6/J33.14) HRSTB (J26.B3)
      ibe_bcot_po      : out    std_logic ;                   -- HARDRESET (J32.5/J33.13) HRST (J26.A3)
      ibepp0_bc_mo     : out    std_logic ;                   -- CLKB (J33.4) CLKLB (J26.D4)
      ibepp0_bc_po     : out    std_logic ;                   -- CLK (J33.3) CLKL (J26.C4)
      ibepp0_clk_mo    : out    std_logic ;                   -- CLKB (J33.4) CLKLB (J26.D4)
      ibepp0_clk_po    : out    std_logic ;                   -- CLK (J33.3) CLKL (J26.C4)
      ibepp1_bc_mo     : out    std_logic ;                   -- CLKB (J33.4) CLKLB (J26.D4)
      ibepp1_bc_po     : out    std_logic ;                   -- CLK (J33.3) CLKL (J26.C4)
      ibepp1_clk_mo    : out    std_logic ;                   -- BCB (J32.4/J33.8) SW_CLKB (J26.F4)
      ibepp1_clk_po    : out    std_logic ;                   -- BC (J32.3/J33.7) SW_CLK (J26.E4)
      ibpp0_o          : out    std_logic_vector (7 downto 0);
      ibpp1_o          : out    std_logic_vector (7 downto 0);
      ibstb_com_o      : out    std_logic ;
      ibstb_l1r_o      : out    std_logic ;
      ibstb_noise_o    : out    std_logic ;
      ibstt_com_o      : out    std_logic ;
      ibstt_l1r_o      : out    std_logic ;
      ibstt_noise_o    : out    std_logic 
   );
   end component;
   component top_outputs_tester
   port (
      clk_bco        : out    std_logic;
      clk_o          : out    std_logic;
      com            : out    std_logic;
      l1r            : out    std_logic;
      outsigs        : out    std_logic_vector (15 downto 0);
      reg_com_enable : out    std_logic_vector (15 downto 0);
      reg_control    : out    std_logic_vector (15 downto 0);
      rst_o          : out    std_logic;
      strobe40       : out    std_logic
   );
   end component;


begin

   -- Instance port mappings.
   Udut : top_outputs
      port map (
         clk              => clk,
         clk_bco_i        => clk_bco,
         com_i            => com,
         outsigs_i        => outsigs,
         reg_com_enable_i => reg_com_enable,
         reg_control_i    => reg_control,
         rst              => rst,
         strobe40_i       => strobe40,
         dbg_outsigs_o    => open,
         ibe_bco_mo       => ibe_bco_mo,
         ibe_bco_po       => ibe_bco_po,
         ibe_bcot_mo      => ibe_bcot_mo,
         ibe_bcot_po      => ibe_bcot_po,
         ibepp0_bc_mo     => ibepp0_bc_mo,
         ibepp0_bc_po     => ibepp0_bc_po,
         ibepp0_clk_mo    => ibepp0_clk_mo,
         ibepp0_clk_po    => ibepp0_clk_po,
         ibepp1_bc_mo     => ibepp1_bc_mo,
         ibepp1_bc_po     => ibepp1_bc_po,
         ibepp1_clk_mo    => ibepp1_clk_mo,
         ibepp1_clk_po    => ibepp1_clk_po,
         ibpp0_o          => ibpp0_o,
         ibpp1_o          => ibpp1_o,
         ibstb_com_o      => open,
         ibstb_l1r_o      => open,
         ibstb_noise_o    => open,
         ibstt_com_o      => open,
         ibstt_l1r_o      => open,
         ibstt_noise_o    => open
      );
   Utst : top_outputs_tester
      port map (
         outsigs        => outsigs,
         clk_o          => clk,
         clk_bco        => clk_bco,
         com            => com,
         l1r            => l1r,
         reg_com_enable => reg_com_enable,
         reg_control    => reg_control,
         rst_o          => rst,
         strobe40       => strobe40
      );

end struct;
