-- VHDL Entity hsio.trigger_top_tb.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--



entity trigger_top_tb is
-- Declarations

end trigger_top_tb ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- hsio.trigger_top_tb.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.std_logic_arith.ALL;
use ieee.std_logic_unsigned.ALL;
library utils;
use utils.pkg_types.ALL;
library hsio;
use hsio.pkg_hsio_globals.ALL;


architecture struct of trigger_top_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal HI           : std_logic;
   signal LO           : std_logic;
   signal bcid         : std_logic_vector(11 downto 0);
   signal bcid_l1a     : std_logic_vector(11 downto 0);
   signal bcr_all      : std_logic;
   signal busy         : std_logic;
   signal busy_all     : std_logic;
   signal busy_ext     : std_logic;
   signal clk          : std_logic;
   signal clk160       : std_logic;
   signal clk40        : std_logic;
   signal command      : slv16;
   signal dbg_trig_ext : std_logic;
   signal ecr_all      : std_logic;
   signal l0id         : std_logic_vector(31 downto 0);
   signal l0id_l1      : std_logic_vector(7 downto 0);
   signal lemo_bcr     : std_logic;
   signal lemo_ecr     : std_logic;
   --bcid_l1a       : in     std_logic_vector (15 downto 0);
--com_abc_o      : in     std_logic;
--l1id           : in     slv16;
--l1r_abc_o      : in     std_logic;
   signal lemo_trig    : std_logic;
   -- locallink tx interface
   signal lls          : t_llsrc;
   signal ocraw_start  : std_logic;
   signal outsigs_o    : std_logic_vector(15 downto 0);
   signal pretrig      : std_logic;
   signal rawsigs      : std_logic_vector(15 downto 0);
   -- registers
   signal reg          : t_reg_bus;
   signal rst          : std_logic;
   signal strobe40     : std_logic;
   signal tb_bcount    : std_logic_vector(15 downto 0);
   signal tb_flags     : std_logic_vector(7 downto 0);
   signal tb_tcount    : std_logic_vector(15 downto 0);
   signal tdc_code     : std_logic_vector(19 downto 0);
   signal tdc_counter1 : std_logic_vector(31 downto 0);
   signal tdc_counter2 : std_logic_vector(31 downto 0);
   signal tick         : std_logic_vector(MAX_TICTOG downto 0);
   signal tlu_busy     : std_logic;
   signal tlu_tclk     : std_logic;
   signal tlu_trig     : std_logic;
   signal tog          : std_logic_vector(MAX_TICTOG downto 0);
   signal trg_all_mask : std_logic_vector(15 downto 0);
   signal trig40       : std_logic;
   signal trig80       : std_logic;
   signal trig_out     : std_logic;


   -- Component Declarations
   component trigger_top
   port (
      busy_i            : in     std_logic ;
      clk               : in     std_logic ;
      clk160ps          : in     std_logic ;
      clk40             : in     std_logic ;
      command           : in     std_logic_vector (15 downto 0);
      lemo_bcr_i        : in     std_logic ;
      lemo_ecr_i        : in     std_logic ;
      lemo_trig_i       : in     std_logic ;
      lld_i             : in     std_logic ;
      ocraw_start_i     : in     std_logic ;
      rawsigs_i         : in     std_logic_vector (15 downto 0);
      -- registers
      reg               : in     t_reg_bus ;
      rst               : in     std_logic ;
      s40               : in     std_logic ;
      tick              : in     std_logic_vector (34 downto 0);
      tlu_trig_i        : in     std_logic ;
      tog               : in     std_logic_vector (34 downto 0);
      twin_open_i       : in     std_logic ;
      bcid_l1a_o        : out    std_logic_vector (11 downto 0);
      bcid_o            : out    std_logic_vector (11 downto 0);
      bcr_all_o         : out    std_logic ;
      busy_all_o        : out    std_logic ;
      busy_ext_o        : out    std_logic ;
      dbg_trig_ext_o    : out    std_logic ;
      ecr_all_o         : out    std_logic ;
      l0id_l1_o         : out    std_logic_vector (7 downto 0);
      l0id_o            : out    std_logic_vector (31 downto 0);
      -- locallink tx interface
      lls_o             : out    t_llsrc ;
      outsigs_o         : out    std_logic_vector (15 downto 0);
      pretrig_o         : out    std_logic ;
      tb_bcount_o       : out    std_logic_vector (15 downto 0);
      tb_flags_o        : out    std_logic_vector (7 downto 0);
      tb_tcount_o       : out    std_logic_vector (15 downto 0);
      tdc_calib_edge0_o : out    std_logic ;
      tdc_code_o        : out    std_logic_vector (19 downto 0);
      tdc_counter1_o    : out    std_logic_vector (31 downto 0);
      tdc_counter2_o    : out    std_logic_vector (31 downto 0);
      tlu_busy_o        : out    std_logic ;
      tlu_tclk_o        : out    std_logic ;
      trg_all_mask_o    : out    std_logic_vector (15 downto 0);
      trig40_o          : out    std_logic ;
      trig80_o          : out    std_logic ;
      trig_out_o        : out    std_logic 
   );
   end component;
   component trigger_top_tester
   port (
      --bcid_l1a       : in     std_logic_vector (15 downto 0);
      --com_abc_o      : in     std_logic;
      --l1id           : in     slv16;
      --l1r_abc_o      : in     std_logic;
      tdc_edge0   : out    std_logic ;
      tlu_trig    : out    std_logic ;
      lemo_trig   : out    std_logic ;
      lemo_ecr    : out    std_logic ;
      lemo_bcr    : out    std_logic ;
      busy        : out    std_logic ;
      ocraw_start : out    std_logic ;
      command     : out    slv16 ;
      reg         : out    t_reg_bus ;
      rawsigs     : out    std_logic_vector (15 downto 0);
      strobe40    : out    std_logic ;
      clk40_o     : out    std_logic ;
      clk160_o    : out    std_logic ;
      clk_o       : out    std_logic ;
      rst_o       : out    std_logic 
   );
   end component;
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;
   component ticks_gen
   generic (
      SIM_MODE : integer := 0;
      CLK_MHZ  : integer := 80
   );
   port (
      clk      : in     std_logic;
      rst      : in     std_logic;
      tick_o   : out    std_logic_vector (MAX_TICTOG downto 0);
      toggle_o : out    std_logic_vector (MAX_TICTOG downto 0)
   );
   end component;


begin

   -- Instance port mappings.
   Udut : trigger_top
      port map (
         busy_i            => busy,
         clk               => clk,
         clk160ps          => clk160,
         clk40             => clk40,
         command           => command,
         lemo_bcr_i        => lemo_bcr,
         lemo_ecr_i        => lemo_ecr,
         lemo_trig_i       => lemo_trig,
         lld_i             => HI,
         ocraw_start_i     => ocraw_start,
         rawsigs_i         => rawsigs,
         reg               => reg,
         rst               => rst,
         s40               => strobe40,
         tick              => tick,
         tlu_trig_i        => tlu_trig,
         tog               => tog,
         twin_open_i       => HI,
         bcid_l1a_o        => bcid_l1a,
         bcid_o            => bcid,
         bcr_all_o         => bcr_all,
         busy_all_o        => busy_all,
         busy_ext_o        => busy_ext,
         dbg_trig_ext_o    => dbg_trig_ext,
         ecr_all_o         => ecr_all,
         l0id_l1_o         => l0id_l1,
         l0id_o            => l0id,
         lls_o             => lls,
         outsigs_o         => outsigs_o,
         pretrig_o         => pretrig,
         tb_bcount_o       => tb_bcount,
         tb_flags_o        => tb_flags,
         tb_tcount_o       => tb_tcount,
         tdc_calib_edge0_o => open,
         tdc_code_o        => tdc_code,
         tdc_counter1_o    => tdc_counter1,
         tdc_counter2_o    => tdc_counter2,
         tlu_busy_o        => tlu_busy,
         tlu_tclk_o        => tlu_tclk,
         trg_all_mask_o    => trg_all_mask,
         trig40_o          => trig40,
         trig80_o          => trig80,
         trig_out_o        => trig_out
      );
   Utst : trigger_top_tester
      port map (
         tdc_edge0   => open,
         tlu_trig    => tlu_trig,
         lemo_trig   => lemo_trig,
         lemo_ecr    => lemo_ecr,
         lemo_bcr    => lemo_bcr,
         busy        => busy,
         ocraw_start => ocraw_start,
         command     => command,
         reg         => reg,
         rawsigs     => rawsigs,
         strobe40    => strobe40,
         clk40_o     => clk40,
         clk160_o    => clk160,
         clk_o       => clk,
         rst_o       => rst
      );
   Umpower : m_power
      port map (
         hi => HI,
         lo => LO
      );
   Uticksgen : ticks_gen
      generic map (
         SIM_MODE => 1,
         CLK_MHZ  => 80
      )
      port map (
         tick_o   => tick,
         toggle_o => tog,
         clk      => clk,
         rst      => rst
      );

end struct;
