-- VHDL Entity atlys.itsdaq_clk_rst.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library utils;
use utils.pkg_types.all;

entity itsdaq_clk_rst is
   port( 
      --#clockpinforAtlysrevCboard
      clk100_i        : in     std_logic;
      rst_o           : out    std_logic;
      clk160_o        : out    std_logic;
      clk80_o         : out    std_logic;
      clk40_o         : out    std_logic;
      ext_bco_i       : in     std_logic;
      rst_btn_ni      : in     std_logic;
      rst_no          : out    std_logic;
      clk_ext_sel_i   : in     std_logic;
      ext_por_no      : out    std_logic;
      strobe40_o      : out    std_logic;
      clk125_locked_o : out    std_logic;
      clk125_o        : out    std_logic;
      clk_locked_o    : out    std_logic
   );

-- Declarations

end itsdaq_clk_rst ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- atlys.itsdaq_clk_rst.struct
--
-- Created by Matt Warren 2014
--

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library utils;
use utils.pkg_types.all;
library unisim;
use unisim.VCOMPONENTS.all;
use ieee.numeric_std.all;


architecture struct of itsdaq_clk_rst is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk125        : std_logic;
   signal rst           : std_logic;
   signal clk40         : std_logic;
   signal clk80         : std_logic;
   signal clk160        : std_logic;
   signal clkn40        : std_logic;
   signal clk40a_locked : std_logic;
   signal ext_por       : std_logic;
   signal clk40a        : std_logic;
   signal clk40b        : std_logic;
   signal clk80a        : std_logic;
   signal clk80b        : std_logic;
   signal clk160a       : std_logic;
   signal clk160b       : std_logic;
   signal clk40b_locked : std_logic;
   signal clkn40a       : std_logic;
   signal clkn40b       : std_logic;
   signal clk100        : std_logic;
   signal rst40a        : std_logic;
   signal rst40b        : std_logic;


   -- Component Declarations
   component cg_dcm_125
   port (
      CLK100_IN : in     std_logic;
      RESET     : in     std_logic;
      CLK100    : out    std_logic;
      CLK125    : out    std_logic;
      LOCKED    : out    std_logic
   );
   end component;
   component cg_dcm_40
   port (
      -- Clock in ports
      BCO_IN    : in     std_logic ;
      -- Clock out ports
      CLK40     : out    std_logic ;
      CLK80     : out    std_logic ;
      CLK160    : out    std_logic ;
      CLK40_180 : out    std_logic ;
      -- Status and control signals
      RESET     : in     std_logic ;
      LOCKED    : out    std_logic ;
      CLK_VALID : out    std_logic 
   );
   end component;
   component cg_dcm_4080160
   port (
      CLK100_IN : in     std_logic;
      RESET     : in     std_logic;
      CLK100    : out    std_logic;
      CLK160    : out    std_logic;
      CLK40     : out    std_logic;
      CLK80     : out    std_logic;
      LOCKED    : out    std_logic
   );
   end component;
   component xilinx_reset
   generic (
      PIPE_LEN : integer := 15
   );
   port (
      clk      : in     std_ulogic ;
      ready_i  : in     std_logic ;
      reset_no : out    std_ulogic ;
      reset_o  : out    std_ulogic 
   );
   end component;
   component BUFG
   port (
      I : in     std_ulogic;
      O : out    std_ulogic
   );
   end component;
   component BUFGMUX
   generic (
      CLK_SEL_TYPE : string := "SYNC"
   );
   port (
      I0 : in     std_ulogic;
      I1 : in     std_ulogic;
      S  : in     std_ulogic;
      O  : out    std_ulogic
   );
   end component;
   component strobe40_gen
   port (
      strobe40_o : out    std_logic ;
      clk40      : in     std_logic ;
      rst        : in     std_logic ;
      clk        : in     std_logic 
   );
   end component;


begin

   -- ModuleWare code(v1.12) for instance 'U_1' of 'buff'

   -- ModuleWare code(v1.12) for instance 'U_3' of 'buff'

   -- ModuleWare code(v1.12) for instance 'U_4' of 'buff'

   -- ModuleWare code(v1.12) for instance 'U_5' of 'buff'

   -- ModuleWare code(v1.12) for instance 'U_6' of 'buff'
   rst_o <= rst;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'buff'
   clk125_o <= clk125;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'buff'
   clk_locked_o <= clk40a_locked;

   -- ModuleWare code(v1.12) for instance 'U_13' of 'inv'
   rst40a <= not(clk40a_locked);

   -- ModuleWare code(v1.12) for instance 'U_14' of 'inv'
   rst40b <= not(clk40b_locked);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'

   -- Instance port mappings.
   Udcm125 : cg_dcm_125
      port map (
         CLK100_IN => clk100_i,
         CLK100    => open,
         CLK125    => clk125,
         RESET     => ext_por,
         LOCKED    => clk125_locked_o
      );
   Udcm40b : cg_dcm_40
      port map (
         BCO_IN    => ext_bco_i,
         CLK40     => open,
         CLK80     => open,
         CLK160    => open,
         CLK40_180 => open,
         RESET     => ext_por,
         LOCKED    => clk40b_locked,
         CLK_VALID => open
      );
   Udcm40a : cg_dcm_4080160
      port map (
         CLK100_IN => clk100_i,
         CLK100    => clk100,
         CLK40     => clk40,
         CLK80     => clk80,
         CLK160    => clk160,
         RESET     => ext_por,
         LOCKED    => clk40a_locked
      );
   Uxreset : xilinx_reset
      generic map (
         PIPE_LEN => 15
      )
      port map (
         clk      => clk100_i,
         ready_i  => rst_btn_ni,
         reset_no => ext_por_no,
         reset_o  => ext_por
      );
   Uxreset1 : xilinx_reset
      generic map (
         PIPE_LEN => 15
      )
      port map (
         clk      => clk80,
         ready_i  => clk40a_locked,
         reset_no => rst_no,
         reset_o  => rst
      );
   Ubufg40 : BUFG
      port map (
         O => clk40_o,
         I => clk40
      );
   Ubufg80 : BUFG
      port map (
         O => clk80_o,
         I => clk80
      );
   Ubufg160 : BUFG
      port map (
         O => clk160_o,
         I => clk160
      );
   Ubufgmux40 : BUFGMUX
      port map (
         O  => open,
         I0 => clk40a,
         I1 => clk40b,
         S  => clk_ext_sel_i
      );
   Ubufgmux40n : BUFGMUX
      port map (
         O  => open,
         I0 => clkn40a,
         I1 => clkn40b,
         S  => clk_ext_sel_i
      );
   Ubufgmux80 : BUFGMUX
      port map (
         O  => open,
         I0 => clk80a,
         I1 => clk80b,
         S  => clk_ext_sel_i
      );
   Ubufgmux160 : BUFGMUX
      port map (
         O  => open,
         I0 => clk160a,
         I1 => clk160b,
         S  => clk_ext_sel_i
      );
   Ustrb40 : strobe40_gen
      port map (
         strobe40_o => strobe40_o,
         clk40      => clk40,
         rst        => rst,
         clk        => clk80
      );

end struct;
