-- VHDL Entity hsio.idelay_block_not.symbol
--
-- Created by Matt Warren 2014
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity idelay_block_not is
   port( 
      clk                    : in     std_logic;
      ddrdata_i              : in     std_logic;
      rst                    : in     std_logic;
      str_swap_i             : in     std_logic;
      dbg_ddrdata_idelayed_o : out    std_logic;
      stream0_o              : out    std_logic;
      stream1_o              : out    std_logic
   );

-- Declarations

end idelay_block_not ;

-- VHDL from Block Diagram 
-- Generated by Mentor Graphics HDL Designer(TM) 2013.1 (Build 6) 
--
-- hsio.idelay_block_not.struct
--
-- Created by Matt Warren 2014
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;
library unisim;
use unisim.all;
use UNISIM.VCOMPONENTS.all;


architecture struct of idelay_block_not is

   -- Architecture declarations

   -- Internal signal declarations
   signal HI      : std_logic;
   signal LO      : std_logic;
   signal stream0 : std_logic;
   signal stream1 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   signal mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   signal mw_U_2reg_cval : std_logic;

   -- Component Declarations
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   stream0_o <= stream1 when (str_swap_i = '1') else stream0;
   stream1_o <= stream0 when (str_swap_i = '1') else stream1;


   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   stream0 <= mw_U_0reg_cval;
   prcu_0seq: process (clk)begin
      if (clk'event and clk='1') then
         if (rst = '1' or rst = 'H') then
            mw_U_0reg_cval <= '0';
         else
            mw_U_0reg_cval <= ddrdata_i;
         end if;
      end if;
   end process prcu_0seq;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   stream1 <= mw_U_2reg_cval;
   prcu_2seq: process (clk)begin
      if (clk'event and clk='0') then
         if (rst = '1' or rst = 'H') then
            mw_U_2reg_cval <= '0';
         else
            mw_U_2reg_cval <= ddrdata_i;
         end if;
      end if;
   end process prcu_2seq;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'buff'
   dbg_ddrdata_idelayed_o <= ddrdata_i;

   -- Instance port mappings.
   Umpower : m_power
      port map (
         hi => HI,
         lo => LO
      );

end struct;
