set timestamp [clock seconds]
set ts_string "[clock format $timestamp]"
#puts "Setting timestamp to: $timestamp = [format 0x%04X $timestamp] = $ts_string"
#puts "$argv"

set tsdir $argv
set tsfile "timestamp.vhd"

exec echo "-- timestamp.vhd generated by mkfiles/timestamp.tcl:"     > $tsdir/$tsfile
exec echo "-- $ts_string = $timestamp = [format 0x%04X $timestamp]" >> $tsdir/$tsfile

exec echo "library ieee;"                                        >> $tsdir/$tsfile
exec echo "use ieee.std_logic_1164.all;"                         >> $tsdir/$tsfile
exec echo "use ieee.std_logic_arith.all;"                        >> $tsdir/$tsfile
exec echo "use ieee.std_logic_unsigned.all;"                     >> $tsdir/$tsfile
exec echo ""                                                     >> $tsdir/$tsfile
exec echo "entity timestamp is"                                  >> $tsdir/$tsfile
exec echo "   port( ts_o : out std_logic_vector (31 downto 0));" >> $tsdir/$tsfile
exec echo "end timestamp ;"                                      >> $tsdir/$tsfile
exec echo ""                                                     >> $tsdir/$tsfile
exec echo "architecture rtl of timestamp is"                     >> $tsdir/$tsfile
exec echo "begin"                                                >> $tsdir/$tsfile
exec echo "  ts_o <= conv_std_logic_vector($timestamp, 32);"     >> $tsdir/$tsfile
exec echo "end architecture rtl;"                                >> $tsdir/$tsfile
exec echo ""                                                     >> $tsdir/$tsfile
exec cat $tsdir/$tsfile

puts "Created $tsdir/$tsfile. $timestamp [format 0x%04X $timestamp]"
puts "$ts_string"

