-- VHDL Entity parser.parser_top_tb.symbol
--
-- Created:
--          by - Matt Warren
--          at - 12:50:24 08/04/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--


entity parser_top_tb is
-- Declarations

end parser_top_tb ;

--
-- VHDL Architecture parser.parser_top_tb.struct
--
-- Created:
--          by - Matt Warren
--          at - 12:50:24 08/04/11
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.2a (Build 7)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
LIBRARY UNISIM;
USE UNISIM.VComponents.ALL;

use work.pkg_hsio_globals.t_llbus;

architecture struct of parser_top_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal abcdata     : std_logic;
   signal clk         : std_logic;
   signal debug_mode  : std_logic;
   signal hi          : std_logic;
   signal ll          : t_llbus;
   signal lo          : std_logic;
   signal rst         : std_logic;
   signal start_hstro : std_logic;


   -- Component Declarations
   component parser_tom_top
   generic (
      STREAM_ID       : integer := 0;
      histogram_width : integer := 16
   );
   port (
      rst           : in     std_logic ;                   -- HSIO switch2, code_reload#
      en            : in     std_logic ;
      abcdata_i     : in     std_logic ;
      start_hstro_i : in     std_logic ;
      debug_mode_i  : in     std_logic ;
      ll_sof_o      : out    std_logic ;
      ll_eof_o      : out    std_logic ;
      ll_src_rdy_o  : out    std_logic ;
      ll_dst_rdy_i  : in     std_logic ;
      ll_data_o     : out    std_logic_vector (15 downto 0);
      --    ll_data_len_o   : out std_logic_vector (15 downto 0);
      clk           : in     std_logic 
   );
   end component;
   component parser_top_tester
   port (
      abcdata      : out    std_logic;
      clk_o        : out    std_logic;
      debug_mode_o : out    std_logic;
      dst_rdy      : out    std_logic;
      rst_o        : out    std_logic;
      start_hstro  : out    std_logic;

      -- Spy on LL, includes copy of dst_rdy
      ll_in        : in     t_llbus
   );
   end component;
   component m_power
   port (
      hi : out    std_logic ;
      lo : out    std_logic 
   );
   end component;


begin

   -- Instance port mappings.
   Udut : parser_tom_top
      generic map (
         STREAM_ID       => 16#F1#,
         histogram_width => 16
      )
      port map (
         rst           => rst,
         en            => hi,
         abcdata_i     => abcdata,
         start_hstro_i => start_hstro,
         debug_mode_i  => debug_mode,
         ll_sof_o      => ll.sof,
         ll_eof_o      => ll.eof,
         ll_src_rdy_o  => ll.src_rdy,
         ll_dst_rdy_i  => ll.dst_rdy,
         ll_data_o     => ll.data,
         clk           => clk
      );
   Utest : parser_top_tester
      port map (
         start_hstro  => start_hstro,
         clk_o        => clk,
         abcdata      => abcdata,
         dst_rdy      => ll.dst_rdy,
         debug_mode_o => debug_mode,
         rst_o        => rst,
         ll_in        => ll
      );
   Um_power : m_power
      port map (
         hi => hi,
         lo => lo
      );

end struct;
